'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
const phases=[{title:<>AUTONOMOUS<br/>INFRASTRUCTURE</>,description:'High-throughput neural backends engineered for deterministic enterprise execution.',name:'INTAKE'},{title:<>NEURAL<br/>ORCHESTRATION</>,description:'Real-time voice synthesis, multi-agent state machines, and zero-latency inference meshes.',name:'NEURAL_ORCHESTRATION'},{title:<>ENTERPRISE<br/>AUTOMATION</>,description:'Distributed execution layers replacing manual operational overhead at 10x throughput.',name:'AUTONOMOUS_EXECUTION'}];
export default function HeroScrubber(){const section=useRef<HTMLElement>(null),canvas=useRef<HTMLCanvasElement>(null),progress=useRef(0);const [p,setP]=useState(0),[fallback,setFallback]=useState(false);
useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const trigger=ScrollTrigger.create({trigger:section.current,start:'top top',end:'+=350%',pin:!reduced,scrub:true,onUpdate:s=>{progress.current=s.progress;setP(s.progress)}});let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({canvas:canvas.current!,alpha:true,antialias:true,powerPreference:'high-performance'});}catch{setFallback(true);return ()=>trigger.kill()}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,0,8.8);const core=new THREE.Group();scene.add(core);const geometries:THREE.BufferGeometry[]=[],materials:THREE.Material[]=[];const wire=(radius:number,detail:number,color:number,opacity:number)=>{const geo=new THREE.IcosahedronGeometry(radius,detail);geometries.push(geo);const mat=new THREE.MeshBasicMaterial({color,wireframe:true,transparent:true,opacity});materials.push(mat);const mesh=new THREE.Mesh(geo,mat);core.add(mesh);return mesh};const crystal=wire(1.07,1,0x00f0ff,.75);wire(1.23,2,0x587d85,.24);wire(.76,1,0x10b981,.6);
const rings:THREE.Mesh[]=[];for(let i=0;i<4;i++){const geo=new THREE.TorusGeometry(1.5+i*.16,i===0?.032:.016,8,180);const mat=new THREE.MeshStandardMaterial({color:i===3?0x00b8c7:0x7c929a,metalness:.9,roughness:.25,emissive:i===3?0x00666e:0x0b151a});geometries.push(geo);materials.push(mat);const ring=new THREE.Mesh(geo,mat);ring.rotation.set(.6+i*.55,.3+i*.7,i*.4);core.add(ring);rings.push(ring)}
const points=new Float32Array(360*3);for(let i=0;i<360;i++){const a=i*2.39996,y=1-(i/359)*2,r=Math.sqrt(1-y*y)*1.32;points.set([Math.cos(a)*r,y*1.32,Math.sin(a)*r],i*3)}const dotsGeo=new THREE.BufferGeometry();dotsGeo.setAttribute('position',new THREE.BufferAttribute(points,3));const dotsMat=new THREE.PointsMaterial({color:0x7affef,size:.018,transparent:true,opacity:.7});geometries.push(dotsGeo);materials.push(dotsMat);core.add(new THREE.Points(dotsGeo,dotsMat));scene.add(new THREE.AmbientLight(0x8fbfcf,3));const light=new THREE.PointLight(0x00f0ff,35);light.position.set(2,3,4);scene.add(light);const resize=()=>{const parent=canvas.current?.parentElement;if(!parent)return;const {width,height}=parent.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()};resize();const observer=new ResizeObserver(resize);observer.observe(canvas.current!.parentElement!);let frame=0;const animate=(t:number)=>{const v=progress.current;core.rotation.y=v*Math.PI*2;core.rotation.z=-.12+v*.25;crystal.rotation.y=reduced?0:t*.00006;const scale=1+Math.sin(v*Math.PI)*.23;core.scale.setScalar(scale);rings.forEach((ring,i)=>{ring.rotation.x=.6+i*.55+v*(i%2?1:-1)*Math.PI;ring.rotation.z=i*.4+v*2});renderer.render(scene,camera);frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return ()=>{cancelAnimationFrame(frame);observer.disconnect();trigger.kill();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());renderer.dispose()};},[]);
const phase=Math.min(2,Math.floor(p*3));return <section ref={section} className="hero" id="core"><div className="hud">{phases.map((item,i)=><div className={phase===i?'hud-segment active':'hud-segment'} key={item.name}><span>0{i+1}</span><span>CORE_SYSTEM: NODE_0{i+1}<small>// {item.name}</small></span><i style={{width:`${Math.max(0,Math.min(1,p*3-i))*100}%`}}/></div>)}</div><div className="hero-stage"><div className="core-visual"><div className="orbital-grid"/><canvas ref={canvas} aria-label="Scroll-controlled crystalline neural core with titanium gimbal rings"/>{fallback&&<div className="fallback-core">◈<small>CORE VISUALIZATION OFFLINE</small></div>}<span className="coordinate top">X: {(p*360).toFixed(2)}° &nbsp; Y: 012.84°</span><span className="coordinate bottom">NEURAL CORE / REV. 003</span></div><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> AUTONOMY, ENGINEERED.</div><p className="hero-index">10XBIN //</p><h1 key={phase}>{phases[phase].title}</h1><p className="hero-sub">Built to think.<br/>Engineered to execute.</p><a className="button primary" href="#dispatch">INITIALIZE PIPELINE <span>↗</span></a></div><aside className="telemetry"><span className="eyebrow">// TELEMETRY: 0{phase+1}</span><div className="telemetry-rule"/><p>{phases[phase].description}</p><div className="mini-bars">{Array.from({length:25},(_,i)=><i key={i} style={{height:`${10+(Math.sin(i*1.3)+1)*13}px`}}/>)}</div><span className="micro">SIGNAL INTEGRITY <b>100%</b></span></aside><div className="hero-bottom"><span>↓ &nbsp; SCRUB TIMELINE TO INITIALIZE TELEMETRY</span><span className="network"><span className="status-dot"/> NETWORK_STATUS: OPTIMAL <small>[LATENCY &lt; 12ms] · DEMO</small></span></div></div><div className="hero-footer"><span>AUTONOMOUS BY DESIGN.</span><span>HUMAN AMBITION. MACHINE PRECISION.</span><span>GLOBAL EDGE ↗</span></div></section>}
